### ISSUE TITLE
fcm send error: request contains an invalid argument

### ISSUE THREAD

**Issue by diwenx** [crow-misia/go-push-receiver#2]
Hi, thanks for creating this library, I found it very useful.
It has been working well until recently. However, recently, any newly registered token cannot be sent notification to (due to "invalid token type" error), while existing (previously registered with the same code) tokens are unaffected.

I tried on both a macOS and Linux machine and were able to reproduce the error with /examples in both cases.

Could you please test it and see if you're also seeing the error? Thanks!

**Comment by diwenx** [comment]
Hmm... after switching to a datacenter network with VPN, I'm able to register valid tokens again. But in my home/residential network, newly registered tokens are still "invalid". Weird.

**Comment by crow-misia** [comment]
I created a new Firebase project and tested it, but no error occurred.

Please reports error messages.

**Comment by diwenx** [comment]
Hi @crow-misia, thanks for the response. As I said, I tested token generation again on a different network, and the error was resolved. However, from my home (residential ISP) network, I can get token registered successfully but when I attempt to send push messages to these newly registered tokens, I got the following error message:

> fcm send error: http error status: 400; reason: request contains an invalid argument; code: invalid-argument; details: Request contains an invalid argument.

I suppose since the error seems to depend on which network I'm in, it probably isn't an implementation issue. So please feel free to close the issue. Thanks again for creating this library.

**Comment by crow-misia** [comment]
All right!
