### ISSUE TITLE
Heartbeat Question

### ISSUE THREAD

**Issue by serkanaslan34** [crow-misia/go-push-receiver#7]
Hi crow-misia,

Im trying to convert your go code to C#.
Could you explain to me why do you use Heartbeat.start method for send heartbeat ping with timer ? 

You can set LoginRequest like this and you will receive Heartbeatping and after that you can send HeartbeatAck

   loginRequest.Setting.Add(new Setting() { Name = FirebaseConstant.kHeartbeatIntervalSettingName, Value = "10000" });

**Comment by crow-misia** [comment]
I did not know about that setting.

I think it would make a difference which one is the primary transmitter of heartbeats, so it would be better if users could choose!

**Comment by serkanaslan34** [comment]
Thanks for your answer, I was just wondering. Thanks.
